In [5]:
import numpy as np

# 1. Create a NumPy 1D-array with 10 elements, then reshape the array into a 2x5 matrix. 

In [14]:
my_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(my_array)
print(my_array.reshape(2,5))

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# 2. Create a second NumPy array with 5 elements, and join it to the first array using the concatenate function.

In [18]:
second_array = np.array([11, 12, 13, 14, 15])
print(np.concatenate((my_array, second_array)))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
