<a href="https://colab.research.google.com/github/ranvirsahota/AiCore/blob/pandas/7_numpy_array_operations/notebook_lesson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Array Operations

> __`numpy` provides a lot of mathematical functions via easy to use notation__

Most of the operations are done "element-wise" (each element with respective elements of the other array):
- addition: `+`
- subtraction: `-`
- multiplication: `*`
- bitwise operations (when array is boolean)

and many others (__see [here](https://scipy-lectures.org/intro/numpy/operations.html) for more examples__)

In [14]:
import numpy as np

arr1 = np.full((3, 3), fill_value = 5)
identity_1 = np.eye(arr1.shape[0], dtype='int64')
print(arr1)
print('    +    ')
print(identity_1)
print('    =    ')
print(arr1 + identity_1)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
    +    
[[1 0 0]
 [0 1 0]
 [0 0 1]]
    =    
[[6 5 5]
 [5 6 5]
 [5 5 6]]


## Mathematical functions


> `numpy` provides a lot of math functions (e.g. trigonometric)

Traits:
- Works on any array (usually element-wise) with some edge-case exceptions
- Optimized C implementations
- Provided in the `np` namespace

> All available operations are listed [here](https://numpy.org/doc/stable/reference/routines.math.html)

Let's see an example below:

In [15]:
# np.e and np.pi are predefined constant

(np.cos(arr1) - np.sin(arr1) ** 3) / (np.eye(arr1.shape[0]) * np.e + 0.1)

array([[ 0.41352406, 11.65427351, 11.65427351],
       [11.65427351,  0.41352406, 11.65427351],
       [11.65427351, 11.65427351,  0.41352406]])

## Linear algebra operations

> `numpy` provides linear algebra functionalities __located within `np.linalg` submodule__

See [here](https://numpy.org/doc/stable/reference/routines.linalg.html) for available functionalities.

Some of them are provided as overloaded operations, namely __matrix multiplication__:

In [ ]:
# Inner dimensions must match!

X, y = np.random.randn(10, 5), np.random.randn(6, 3)

(X @ y).shape

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 6 is different from 5)

In [ ]:
x = np.ndarray((2, 3)

TypeError: Cannot interpret '3' as a data type

In [16]:
A = np.random.randn(10)
B = np.random.randn(10)

np.inner(A, B)

1.3398373214198258

In [17]:
# Eigen values

np.linalg.eig(np.random.randn(10, 10))

(array([-3.01601802+0.j        , -2.2552013 +0.90780931j,
        -2.2552013 -0.90780931j,  1.77031797+2.45474834j,
         1.77031797-2.45474834j,  1.38320266+1.4254583j ,
         1.38320266-1.4254583j ,  1.73165837+0.j        ,
        -0.01720827+0.50123073j, -0.01720827-0.50123073j]),
 array([[-0.07192262+0.j        ,  0.04249584+0.13861783j,
          0.04249584-0.13861783j, -0.0544982 -0.11015017j,
         -0.0544982 +0.11015017j,  0.45356989-0.00247035j,
          0.45356989+0.00247035j,  0.34243971+0.j        ,
         -0.12294897-0.25575885j, -0.12294897+0.25575885j],
        [ 0.19042422+0.j        , -0.1094781 -0.28161034j,
         -0.1094781 +0.28161034j,  0.04730539-0.09470476j,
          0.04730539+0.09470476j,  0.21181605+0.13332981j,
          0.21181605-0.13332981j,  0.33549038+0.j        ,
         -0.09007181-0.1909502j , -0.09007181+0.1909502j ],
        [ 0.41999438+0.j        ,  0.31760584-0.03640494j,
          0.31760584+0.03640494j,  0.1239054 +0.02170018j

## Accessing elements


> `numpy` allows us to access data in multiple ways

Before we move on to accessing data (and advanced way to do that) you should keep the following in mind (__all the time!__):
- __ALWAYS USE `numpy` OPERATIONS__
- __NO FOR LOOPS KNOWN FROM PYTHON__ (every operation you do should be done purely in `numpy`)
- You will learn more and more ways to avoid loops as we go through the course materials

## Standard index-based item

First, let's create a `2D` array we will use:

In [18]:
matrix = np.arange(20).reshape(5, 4)

matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [19]:
# Obtaining single element

matrix[0, 0], matrix[1, 0], matrix[0, 1], matrix[2][0]

(0, 4, 1, 8)

In [20]:
# first row

matrix[0]

array([0, 1, 2, 3])

In [21]:
# : means all elements
# 0 means 0th column

matrix[:, 0]

array([ 0,  4,  8, 12, 16])

In [22]:
# Rows from second upwards
matrix[2:]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [23]:
# Columns from second upwards
matrix[:, 2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [24]:
# Rows from zeroth to third, column 0
matrix[:3, 0]

array([0, 4, 8])

In [37]:
# Inverse of columns

matrix[:, ::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12],
       [19, 18, 17, 16]])

In [ ]:
matrix[::-1, ::-1]

array([[19, 18, 17, 16],
       [15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [26]:
matrix[::-3, ::-2]

array([[19, 17],
       [ 7,  5]])

In [ ]:
# change to 3D tensor
temp = matrix.reshape(2, 2, -1)
temp.shape

(2, 2, 5)

In [ ]:
# Same as temp[:, :, -1] e.g. last element from last dimension
# Rest left in-tact
# 2, 2 as we have created five 2,2 matrices

temp[..., -1]

array([[ 4,  9],
       [14, 19]])

## Fancy indexing

One of `numpy`'s killer features:

> __Fancy indexing allows us to choose elements FROM ANY DIMENSION based on indices we provide__

![](https://github.com/AI-Core/Content-Public/blob/main/Content/units/Data-Handling/1.%20Numpy/1.%20Numpy%20-%20Array%20Operations/images/numpy_fancy_indexing.png?raw=1)

Once again, we will use our `2D` matrix:

In [38]:
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [39]:
# Column 0 and 2
matrix[:, [0, 2]]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [40]:
# Take last row twice

matrix[[-1, -1]]

array([[16, 17, 18, 19],
       [16, 17, 18, 19]])

In [41]:
# Shuffle rows using indices

indices = np.arange(matrix.shape[0])
print(indices)
permuted = np.random.permutation(indices)
print(permuted)

matrix[permuted]

[0 1 2 3 4]
[0 1 2 3 4]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [42]:
# Obtain rows based on boolean values

matrix[[True, True, False, True, False]]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [43]:
# Obtaining only elements which fulfill condition
# In this case elements larger than 5

print(matrix > 5)

# Array has to be flat as it lost it's N x N structure
matrix[matrix > 5]

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# Key Takeaways

- Numpy provides several mathematical functions that can be applied element-wise on array items. The main functions include:
	- Addition
	- Subtration
	- Multiplication
	- Division
	- Bitwise operations
- Numpy also provides trigonometric and linear algebra functions
- To access data elements in Numpy, it's strongly suggested to avoid using Python loops and to use Numpy operations instead

# More Resources
- Numpy - Fundmentals: https://youtu.be/Lfd776JSicY?feature=shared&t=3242
 - Start at **54:02** and end at **1:16:57**
 - Goes thorugh:
   - aggregation functions,
   - indexing and slicing numpy arrays